
soloCBmatchWLtype: "1MM_multi_Nbase_pseudocounts" 
soloUMIfiltering: "MultiGeneUMI_CR"
soloUMIdedup: "1MM_CR"
outFilterScoreMinOverLread: 0.3
outFilterMatchNminOverLread: 0.3
runThreadN: 8
soloMultiMappers: "EM"
